### PR TITLE
Added Binary Search Algorithm

### PR DESCRIPTION
**Pull request by TharinduDilshan**
### What have you Changed(must)

Added Binary Search Algorithm in C#

### Issue no.(must) - C# #440

Pr will be closed and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder.
- [x] I am following clean code and Documentation.
- [x] I have added title and what program will do first in the file.

### CODE REVIEW

**Review by div-bargali — CHANGES_REQUESTED** [review]
Please do not delete the readme.md file

**Comment by TharinduDilshan** [comment]
Hi I added the readme.md file

**Review by TharinduDilshan — COMMENTED** [review]
Done

**Review by TharinduDilshan — COMMENTED** [review]
done

**Pull request merged**
