### PR TITLE
Add Saikrishna0422 as a contributor

### PR DESCRIPTION
**Pull request by SaiKrishna0422**
### What have you Changed(must)

I added Binary search tree code in c. Can you please check it once and add my PR with Hacktoberfest

### Issue no.(must) - #

Pr will be closed and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [ ] This issue was assigned to me if not it will marked as spam.
- [ ] My file is in proper folder.
- [ ] I am following clean code and Documentation.
- [ ] I have added title and what program will do first in the file.

### CODE REVIEW

**Review by hemanth-kotagiri — COMMENTED** [review]
Thanks for the PR @SaiKrishna0422 . But, a Binary Search Tree implementation was already merged into the master of the upstream repository. Here's the PR: #267 .
Here are a few things to take note of before raising another PR in any repository:
1. Always write clean and well-structured code and maintain proper indentation.
2. **Always make sure you add the file in the right directory.** This PR that you've raised is not in the right directory. That is if you are working on any algorithm related to trees here is the directory for you to write code: ``Data-Structures-and-Algorithms/C/Data-Structures/Tree/``
3. Last, but most importantly, you are not maintaining the extension of the language of the code that you have written. Please do add the extension.
4. **Always read contribution guidelines** of a repository before raising a PR.

Please take care of these things before you contribute to any repository.

Thanks!

**Comment by hemanth-kotagiri** [comment]
@div-bargali you can add the label: ``duplicate`` and close this PR.

**Comment by div-bargali** [comment]
> @div-bargali you can add the label: `duplicate` and close this PR. Also, are you open to taking in collaborators? If so, I would be grateful to join!

@hemanth-kotagiri Sure, join our discord channel and we can continue this conversation there.

**Comment by hemanth-kotagiri** [comment]
@div-bargali Awsome! I have joined the server. Thanks!

**Pull request closed without merging**
