### PR TITLE
Revert "Add Operations of Array by Gaurisha R Srivastava"

### PR DESCRIPTION
**Pull request by Gaurisha21**
Reverts div-bargali/Data-Structures-and-Algorithms#90

### CODE REVIEW

**Comment by div-bargali** [comment]
Why do you want to revert it? @Gaurisha21

**Comment by Gaurisha21** [comment]
> Why do you want to revert it? @Gaurisha21

Because I had not Opened an Issue for it

**Comment by div-bargali** [comment]
That was before the rule changes. Since it was merged, it means it is valid PR and accepted.

**Comment by Gaurisha21** [comment]
> That was before the rule changes. Since it was merged, it means it is valid PR and accepted.

Oh okay, I am really sorry. I am really new and did not know the actual working amd rules. 
But now I have ipened an Issue for the same. And yuo have assigned it to me, will it work?
Please forgive me for such a newbie mistake.

**Comment by Gaurisha21** [comment]
@div-bargali dear sir, I, hereby, request you to kindly
'Un-Revert' the Pull Request,if possible, as I did not know that it was a valid Pull Request. Sir, I understand that this is highly unprofessional and irritating, but please consider this as I am a total beginner and had no idea on how this works. Please consider this as a valid PR and Un-Revert the merge.

**Pull request closed without merging**
