### PR TITLE
0-1 Knapsack Problem.cpp

### PR DESCRIPTION
**Pull request by kirito-udit**

### CODE REVIEW

**Review by jai2dev — CHANGES_REQUESTED** [review]
open up an issue first and which type of knapsack problem is this ? 0-1 or fractional mention it in the name

**Comment by jai2dev** [comment]
@kirito-udit open up an issue regarding this and then i will merge it

**Comment by kirito-udit** [comment]
I am really sorry for that. I am opening ir ASAP

**Review by jai2dev — CHANGES_REQUESTED** [review]
put this under the section algorithms/dynamic programming

**Comment by jai2dev** [comment]
remove the previous one

**Comment by kirito-udit** [comment]
Yeah, I have created a new PR in the DP folder and have labelled the file accordingly. 
Please mer

**Pull request closed without merging**
