### PR TITLE
Added the code for Queue using Python

### PR DESCRIPTION
**Pull request by ryanvarghese**
Hey @div-bargali , Please merge my pull request.

### CODE REVIEW

**Comment by div-bargali** [comment]
@ryanvarghese  Please follow the required directory structure as mentioned in #1

**Comment by ryanvarghese** [comment]
> @ryanvarghese Please follow the required directory structure as mentioned in #1

I'm confused , where shall i place my file .I placed it in Python/Algorithms folder

**Comment by div-bargali** [comment]
@ryanvarghese  Inside the Python folder make a new folder Data Structures and add the files there.

**Comment by ryanvarghese** [comment]
@div-bargali Done

**Comment by div-bargali** [comment]
Good Job 👍

**Comment by ryanvarghese** [comment]
> Good Job 👍

Thanks a lot

**Pull request merged**
