### PR TITLE
Added Quick Sort

### PR DESCRIPTION
**Pull request by SusnatoPrime007**
I have starred it and contributed to it,please accept my pr.

### CODE REVIEW

**Comment by div-bargali** [comment]
@SusnatoPrime007 I'm sorry this issue was not assigned to you.

**Comment by SusnatoPrime007** [comment]
> @SusnatoPrime007 I'm sorry this issue was not assigned to you.

Can you please assign this to me?I would like to work on this.

**Comment by div-bargali** [comment]
@SusnatoPrime007 Create a new issue Lucky number | Java and make a new PR please.

**Comment by SusnatoPrime007** [comment]
Okay

**Pull request closed without merging**
