### PR TITLE
Depth_first_search.c

### PR DESCRIPTION
**Pull request by PUSHPASINGH00**

### CODE REVIEW

**Review by jai2dev — CHANGES_REQUESTED** [review]
add it in right folder

**Comment by PUSHPASINGH00** [comment]
I added in the C =>Algorithms=>Tree Traversal =>Depth_first_search.c.Is it wrong?

**Comment by jai2dev** [comment]
> I added in the C =>Algorithms=>Tree Traversal =>Depth_first_search.c.Is it wrong?

it is correct but first open up an issue regarding depth first search then i will merge it

**Comment by jai2dev** [comment]
already there

**Pull request closed without merging**
