### PR TITLE
Branch

### PR DESCRIPTION
**Pull request by Gaurisha21**
### What have you Changed(must)

Added new code to add two 2x2 matrix.

### Issue no.(must) - #406 

Pr will be closed and marked as spam. If issue number not found or issue was assigned to someone else. 
Marking as spam can block your account from HacktoberFest.
### Self Check(Tick After Making pull Request)

- [x] This issue was assigned to me if not it will marked as spam.
- [x] My file is in proper folder.
- [x] I am following clean code and Documentation.
- [x] I have added title and what program will do first in the file.

### CODE REVIEW

**Comment by Gaurisha21** [comment]
@div-bargali Sir I do not understand the last point of Self Check in the PR template. Kindly explain me what to do for that and I/'ll make the changes accordingly.

**Comment by div-bargali** [comment]
@Gaurisha21 That just means that you have added comments at the top of your .cpp file with details of the code, and the problem it solves.

**Review by div-bargali — CHANGES_REQUESTED** [review]
Please add some comments at the start of your code.

**Comment by Gaurisha21** [comment]
Okay I will do asap.

**Comment by Gaurisha21** [comment]
> Please add some comments at the start of your code.

I have made the changes. Please confirm if they are okay or do I need to do anything else.

**Comment by Gaurisha21** [comment]
@div-bargali Thank you for providing me the opportunity to contribute in the repository. 
I am grateful to you. I was a total beginner, but now I am familiarized with the concept of GitHub and Open Source Contribution through this Repo.

Sir, I wanted to know that I have made 3 Merged PR in this repo, in the time span of 1st to 31st October 2020, so will my PR be considered for 'Hacktoberfest Accepted' label? And is it possible to reduce the maturing time of PRs?

Thank you

Regards

**Pull request merged**
