### PR TITLE
added implementation stack using array #1

### PR DESCRIPTION
**Pull request by NEENA-XAVIER**
Remind me if any updations are needed!

### CODE REVIEW

**Comment by div-bargali** [comment]
@NEENA-XAVIER Please create a new directory named C/DataStructures and add the file inside it, since there is no directory in the initial commit.

**Comment by NEENA-XAVIER** [comment]
I'll do it right now! @div-bargali

**Comment by NEENA-XAVIER** [comment]
Its done...Hope you will merge @div-bargali

**Comment by div-bargali** [comment]
Merged!

**Pull request merged**
