### PR TITLE
Added 3Sum.cpp (#113)

### PR DESCRIPTION
**Pull request by Anjalikamath**
Please let me know if any changes are required. Thanks !

### CODE REVIEW

**Review by div-bargali — CHANGES_REQUESTED** [review]
Instead of adding the file in `C++/Algorithms` can you add it to a folder named as the algorithms paradigm the problem is based on?
I may be wrong but is if it's an Ad Hoc or Implementaion problem, make a new folder and add it inside of it.
Like `C++/Algorithms/<Algorithm paradigm>/3Sum.cpp`

**Comment by Anjalikamath** [comment]
Can I create a folder "Two_Pointers" and put 3sum.cpp under it ?

**Comment by div-bargali** [comment]
> Can I create a folder "Two_Pointers" and put 3sum.cpp under it ?

@Anjalikamath Of course.

**Comment by Anjalikamath** [comment]
Created  "Two_pointers" folder and added 3Sum.cpp to it.

**Review by div-bargali — APPROVED** [review]

**Comment by div-bargali** [comment]
Merged 🎉

**Pull request merged**
