### PR TITLE
ternary_search in C

### PR DESCRIPTION
**Pull request by Aryan-dev007**

### CODE REVIEW

**Review by div-bargali — CHANGES_REQUESTED** [review]
Please keep the `Searching` folder inside `C/Algorithms/<your folder here>`

**Comment by Aryan-dev007** [comment]
Done !

**Review by div-bargali — CHANGES_REQUESTED** [review]
Why are additional files named .DS_Store addede?

**Comment by Aryan-dev007** [comment]
Removed them.

**Comment by div-bargali** [comment]
@Aryan-dev007 in the root directory please remove .DS_Store and quicksort.java.

**Comment by Aryan-dev007** [comment]
Done!

**Review by div-bargali — APPROVED** [review]

**Comment by Aryan-dev007** [comment]
Thanks!

**Pull request merged**
