### PR TITLE
Create Fibonacci.java

### PR DESCRIPTION
**Pull request by SusnatoPrime007**
Please accept my pull request.

### CODE REVIEW

**Review by div-bargali — CHANGES_REQUESTED** [review]
Please follow proper folder structure, refer to contribution guide for more info.

**Comment by SusnatoPrime007** [comment]
Okay

**Comment by SusnatoPrime007** [comment]
Kindly tell me how to create a folder in your repository

**Comment by SusnatoPrime007** [comment]
> Please follow proper folder structure, refer to contribution guide for more info.

Folder is made properly this time,kindly check.

**Comment by div-bargali** [comment]
@SusnatoPrime007  What I meant was your file should be inside Java/Algorithms/Dynamic Programming/Fibonacci.java

**Review by div-bargali — APPROVED** [review]

**Comment by SusnatoPrime007** [comment]
> @SusnatoPrime007 What I meant was your file should be inside `Java/Algorithms/Dynamic Programming/Fibonacci.java`.
> I will merge this PR but from next time take care of it please.

Surely,a very big thank you to you for this!

**Pull request merged**
