### PR TITLE
Depth_first_search.c

### PR DESCRIPTION
**Pull request by PUSHPASINGH00**

### CODE REVIEW

**Comment by jai2dev** [comment]
@PUSHPASINGH00 did you open an issue regarding this ??

**Comment by PUSHPASINGH00** [comment]
No

**Comment by jai2dev** [comment]
> No

First open an issue regarding bfs and dfs differently then i will merge it

**Comment by PUSHPASINGH00** [comment]
Added issue

**Comment by jai2dev** [comment]
dfs is already there so i cant add this

**Pull request closed without merging**
