### PR TITLE
Created Josephus problem.cpp

### PR DESCRIPTION
**Pull request by Ambareen09**

### CODE REVIEW

**Comment by Ambareen09** [comment]
added josephus problem code

**Comment by Ambareen09** [comment]
added josephus problem code

**Comment by div-bargali** [comment]
@Ambareen09 To maintain a proper directory management 📂 please add the file inside a directory in following structure:
C++/Algorithms/ josephus problem.cpp

**Review by div-bargali — CHANGES_REQUESTED** [review]
Please make the requested changes.

**Comment by Ambareen09** [comment]
Okay sure

**Comment by Ambareen09** [comment]
Thanks!

**Comment by Ambareen09** [comment]
Please add my pull request label to "hacktoberfest-accepted" if you're happy with my contribution and merge it. :)

**Pull request merged**
